# Makefile for RIPE attacks against test.so
# Based on RIPE Makefile
CFLAGS=-fno-stack-protector -no-pie -z execstack
CC=gcc
LDFLAGS=-ldl

all: ripe_attack_test ripe_attack_full

ripe_attack_test: ripe_attack_test.c
	$(CC) $(CFLAGS) ripe_attack_test.c -o ripe_attack_test $(LDFLAGS)

ripe_attack_full: ripe_attack_full.c
	$(CC) $(CFLAGS) ripe_attack_full.c -o ripe_attack_full $(LDFLAGS)

clean:
	rm -f ripe_attack_test ripe_attack_full
